name: CI-CD test-api

on:
  push:
    branches:
      - "master"

env:
  REGISTRY: docker.io
  IMAGE_NAME: "fredericobolsamaisbrasil/test-api"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./api
          file: ./api/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Portainer Service Webhook
        uses: newarifrh/portainer-service-webhook@v1
        with:
          webhook_url: https://1155-2804-7540-1000-277-518f-a52b-d8fb-c856.ngrok-free.app/api/webhooks/50a828ca-4085-4cfc-a861-bc730dacaf48
